// src/lib/ui/checkbox/checkbox.svelte
<script lang="ts">
	import Label from '$ui/text/label.svelte';
	import { createCheckbox } from '@melt-ui/svelte';
	import CheckmarkIndeterminateIcon from './assets/checkmark-indeterminate.svelte';
	import CheckmarkIcon from './assets/checkmark.svelte';

	export let checked = false;
	export let indeterminate = false;
	export let disabled = false;
	export let name: string | undefined = undefined;
	export let label: string | undefined = undefined;
	export let value: string | undefined = undefined;
	export let required = false;

	const {
		elements: { root, input },
		helpers: { isChecked, isIndeterminate }
	} = createCheckbox({
		defaultChecked: indeterminate ? 'indeterminate' : checked,
		disabled,
		name,
		value,
		required
	});

	$: checked = $isChecked;
	$: indeterminate = $isIndeterminate;
</script>

<div class="fp-CheckboxRoot" use:root {...$root}>
	<input
		id="checkbox-input"
		class="fp-CheckboxInput"
		use:input
		{...$input}
		aria-labelledby="checkbox-label"
		aria-describedby="checkbox-description"
	/>
	<span class="fp-CheckboxIndicator" aria-hidden="true">
		{#if $isIndeterminate}
			<CheckmarkIndeterminateIcon class="fp-CheckboxIndeterminate" size="4" />
		{:else if $isChecked}
			<CheckmarkIcon class="fp-CheckboxCheckmark" size="4" />
		{/if}
	</span>
	<Label class="fp-CheckboxLabel" for="checkbox-input" aria-hidden="true" id="checkbox-label">
		{label}
	</Label>
	{#if $$slots.description}
		<span class="fp-CheckboxDescription" id="checkbox-description">
			<slot name="description" />
		</span>
	{/if}
</div>

<style src="./checkbox.css"></style>

// packages/ui/src/lib/ui/checkbox/checkbox.tsx
import { CheckmarkIcon } from '@components/icons';
import { CheckmarkIndeterminateIcon } from '@components/icons/checkmark-indeterminate';
import { Label as LabelPrimitive, Text } from '@components/text';
import { createContext } from '@lib/react/create-context';
import { useComposedRefs } from '@lib/react/use-compose-refs';
import { cx } from 'class-variance-authority';
import React, { useCallback, useId } from 'react';

const [CheckboxContextProvider, useCheckboxContext] = createContext<{ id: string }>('Checkbox');

type RootElement = React.ElementRef<'div'>;
type RootProps = React.ComponentPropsWithoutRef<'div'>;

const Root = React.forwardRef<RootElement, RootProps>((props, ref) => {
  const { className, id: idProp, ...rootProps } = props;
  const generatedId = useId();
  const id = idProp ?? generatedId;

  return (
    <CheckboxContextProvider id={id}>
      <div ref={ref} className={cx(className, 'fp-CheckboxRoot')} {...rootProps} />
    </CheckboxContextProvider>
  );
});

type CheckboxElement = React.ElementRef<'input'>;
type CheckboxProps = React.ComponentPropsWithoutRef<'input'> & {
  indeterminate?: boolean;
};

const Input = React.forwardRef<CheckboxElement, CheckboxProps>((props, forwardedRef) => {
  const { className, indeterminate, ...checkboxProps } = props;
  const { id } = useCheckboxContext('Input');
  const inputRef = useIndeterminateState(indeterminate);
  const ref = useComposedRefs(forwardedRef, inputRef);

  return (
    <>
      <input
        ref={ref}
        className={cx(className, 'fp-CheckboxInput')}
        id={id}
        // VoiceOver on Chrome does not announce the label when simply using htmlFor
        aria-labelledby={`checkbox-label-${id}`}
        aria-describedby={`checkbox-description-${id}`}
        {...checkboxProps}
        type="checkbox"
      />
      <Indicator />
    </>
  );
});

const Indicator = () => {
  return (
    <span className="fp-CheckboxIndicator" aria-hidden="true">
      <CheckmarkIcon className="fp-CheckboxCheckmark" size="4" />
      <CheckmarkIndeterminateIcon className="fp-CheckboxIndeterminate" size="4" />
    </span>
  );
};

type LabelElement = React.ElementRef<'label'>;
type LabelProps = React.ComponentPropsWithoutRef<'label'>;

const Label = React.forwardRef<LabelElement, LabelProps>((props, ref) => {
  const { className, ...labelProps } = props;
  const { id } = useCheckboxContext('Input');
  return <LabelPrimitive aria-hidden="true" ref={ref} className={cx(className, 'fp-CheckboxLabel')} htmlFor={id} id={`checkbox-label-${id}`} {...labelProps} />;
});

type DescriptionElement = React.ElementRef<'label'>;
type DescriptionProps = React.ComponentPropsWithoutRef<'label'>;

const Description = React.forwardRef<DescriptionElement, DescriptionProps>((props, ref) => {
  const { className, ...desriptionProps } = props;
  const { id } = useCheckboxContext('Description');
  return <Text aria-hidden="true" ref={ref} className={cx(className, 'fp-CheckboxDescription')} id={`checkbox-description-${id}`} {...desriptionProps} />;
});

function useIndeterminateState(indeterminate: boolean | undefined) {
  return useCallback(
    (inputElement: HTMLInputElement) => {
      if (!inputElement) {
        return;
      }

      inputElement.indeterminate = !!indeterminate;
    },
    [indeterminate],
  );
}

Root.displayName = 'Checkbox.Root';
Input.displayName = 'Checkbox.Input';
Indicator.displayName = 'Checkbox.Indicator';
Label.displayName = 'Checkbox.Label';
Description.displayName = 'Checkbox.Description';

export { Description, Input, Label, Root };
export type { CheckboxProps };
